### ISSUE TITLE
Event when health reaches 0?

### ISSUE THREAD

**Issue by Readie1593** [JumpmanSr/BailOutMode#2]
Hi this is less of an issue and more if a feature that I would like to see, could you make it possible so that when your heath hits 0 the health bar turn red and the environment flashes red lights or the failed msg pops up just so that i know ive failed (but can still carry on). If you make this a feature, many thanks in advance
Dave directed me here

**Comment by JumpmanSr** [comment]
I'll see what I can do, I haven't played BS in a bit so I'll modify it when I can.

**Comment by yunikoyato** [comment]
any chance on 1.5 version?

**Comment by JumpmanSr** [comment]
Current version still works with 1.5, that being said I will be pushing a minor update tonight with an official 1.5 update and it will now properly hide the energy bar if you fail instead of leaving you with that little stub.
