### ISSUE TITLE
Not working in 1.8

### ISSUE THREAD

**Issue by Mace404** [JumpmanSr/BailOutMode#3]
Saw your message on the front page, but for me it is not working in 1.8.
I get the following in the log:

> [INFO @ 11:42:24 | _] [BailOut] Starting Bailout
> [ERROR @ 11:42:24 | IPA] BailOut Mode BS (1.6.0 compatible) OnApplicationStart: System.NullReferenceException: Object reference not set to an instance of an object
> [ERROR @ 11:42:24 | IPA]   at Ryder.Lightweight.Redirection..ctor (System.Reflection.MethodBase original, System.Reflection.MethodBase replacement, System.Boolean start) [0x00016] in <3245ad3fd5d94d4f954c99394be19757>:0 
> [ERROR @ 11:42:24 | IPA]   at GameEnergyPatches.PatchMethods () [0x0002f] in <3245ad3fd5d94d4f954c99394be19757>:0 
> [ERROR @ 11:42:24 | IPA]   at BailOutModePlugin.OnApplicationStart () [0x0000c] in <3245ad3fd5d94d4f954c99394be19757>:0 
> [ERROR @ 11:42:24 | IPA]   at IPA.Loader.Composite.CompositeIPAPlugin+<>c.<OnApplicationStart>b__3_0 (IPA.Old.IPlugin plugin) [0x00000] in <2264097f91364d159cd3c699313e84c0>:0 
> [ERROR @ 11:42:24 | IPA]   at IPA.Loader.Composite.CompositeIPAPlugin.Invoke (IPA.Loader.Composite.CompositeIPAPlugin+CompositeCall callback, System.String member) [0x00015] in <2264097f91364d159cd3c699313e84c0>:0

**Comment by JumpmanSr** [comment]
Patched, sorry for the delay.
