### ISSUE TITLE
Not working with 1.12.x

### ISSUE THREAD

**Issue by stnzbass** [JumpmanSr/BailOutMode#4]
The mod doesn't work since the last big update. I was wondering if you were planing on updating it. This is easily the mod I miss the most since the update. It would be really appreciated :) 
Thank you!

**Comment by Tefery** [comment]
Yeah pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by BobbieVx** [comment]
I really hope this mod gets updated for 1.12. As an Expert+ player that likes to be challenged with newer and harder difficulty songs this a must have mod to get any enjoyment out of playing maps that are just outside your skill level.

**Comment by william-r-s** [comment]
It's updated in this repository: https://github.com/Zingabopp/BailOutMode

**Comment by JumpmanSr** [comment]
Marking as closed since there is an updated/incorporated into the game now. If anything arrises let me know and I'll update it if needed.
