### ISSUE TITLE
Not working with 1.13.2

### ISSUE THREAD

**Issue by ghost** [JumpmanSr/BailOutMode#5]
No more updates? This was a great plugin! I really miss it!

**Comment by JumpmanSr** [comment]
No fail works like this plugin did, did they revert the changes to no fail?  If they did I can toss an update together or make an "update-proof" version (kinda) let me know, I know it's a bit late now

**Comment by JumpmanSr** [comment]
Updated for 1.16.2, closing issue. See releases tab for binaries.
